name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  ci:
    if: github.repository_owner == 'bombshell-dev'
    uses: bombshell-dev/automation/.github/workflows/publish.yml@main
    secrets: inherit

